const REVIEW_STATUSES = [
  'new result','likely relevant','not relevant','duplicate','needs manual verification','needs official source verification','needs redaction','confidential/blocked','sealed/do not publish','approved private','approved public','rejected'
];
const VISIBILITY_STATUSES = ['admin only','private','public approved','public profile summary only','pending','rejected','needs redaction','do not publish'];
const RELIABILITY_LABELS = ['official court source','appellate opinion','trial court order','trial court filing','transcript','public docket','RECAP/PACER record','official disciplinary record','bar record','judicial commission record','prosecutor office/government record','news/public source','commercial legal research platform','Trellis Law research lead','Westlaw manual upload','Lexis manual upload','UniCourt research lead','Docket Alarm research lead','user-submitted document','law firm website','personal website','marketing profile','review','social media','anonymous','unknown source'];
const RELIABILITY_TAGS = ['verified official source','court-record supported','filed allegation, not adjudicated','appellate finding','disciplinary finding','user-submitted','unverified allegation','self-promotional source','adversarial source','anonymous source','conflicting information','needs admin review','needs official verification','do not publish'];
const KEYWORD_GROUPS = {
  'Judicial Recusal / Disqualification': ['motion to recuse','motion for recusal','recusal motion','judge recusal','judicial recusal','motion to disqualify judge','judicial disqualification','disqualification of judge','verified statement of disqualification','affidavit of bias','affidavit of prejudice','bias','prejudice','impartiality','appearance of impropriety','conflict of interest','ex parte','ex parte communication','improper communication','judge conflict','recusal denied','recusal granted','motion denied recusal','motion granted recusal','reassignment to another judge','transfer to presiding judge','administrative reassignment','Canon 2','Canon 3','judicial ethics','due process recusal','Caperton','Liteky'],
  'Guardian ad Litem / GAL Removal / Disqualification': ['guardian ad litem','GAL','G.A.L.','guardian ad litem report','GAL report','motion to remove guardian ad litem','motion to disqualify guardian ad litem','motion to strike guardian ad litem','motion to strike GAL report','motion to remove GAL','motion to disqualify GAL','GAL bias','guardian ad litem bias','GAL misconduct','guardian ad litem misconduct','GAL conflict','guardian ad litem conflict','GAL ex parte','guardian ad litem ex parte','GAL fees','guardian ad litem fees','excessive GAL fees','GAL investigation','inadequate GAL investigation','one-sided GAL investigation','GAL recommendation','improper GAL recommendation','GAL immunity','guardian ad litem immunity','GAL complaint','guardian ad litem complaint','court-appointed guardian','attorney ad litem','amicus attorney','custody evaluator','parenting coordinator','child representative','best interest attorney','minor’s counsel'],
  'GAL Reports / Expert Reports / Evaluators': ['custody evaluator','custody evaluation','psychological evaluation','parental fitness evaluation','reunification therapy','therapeutic supervision','visitation supervisor','supervised visitation','parenting assessment','best interest report','expert report','motion to strike expert report','motion to exclude expert','Daubert','reliability of expert','bias of evaluator','evaluator conflict','custody evaluator misconduct','forensic evaluator','family therapist','therapist records','therapy notes','minor child therapy','improper therapy recommendation','no-contact recommendation','reunification recommendation','parental alienation','gatekeeping','coercive control allegations','domestic violence assessment'],
  'Attorney Misconduct / Disqualification / Sanctions': ['attorney misconduct','lawyer misconduct','counsel misconduct','motion to disqualify counsel','disqualification of counsel','conflict of interest','attorney conflict','lawyer conflict','sanctions','motion for sanctions','sanctions order','attorney fees sanctions','bad faith litigation','frivolous motion','frivolous filing','Rule 11','discovery abuse','discovery misconduct','false statement to court','misrepresentation to court','fraud on the court','perjury','witness intimidation','witness tampering','retaliation','obstruction','improper contact','communication with represented party','breach of confidentiality','protective order violation','motion to compel sanctions','contempt against attorney','bar complaint','disciplinary complaint','ethics complaint','professional conduct','rules of professional conduct'],
  'Prosecutorial Misconduct / DA Conflict': ['prosecutorial misconduct','prosecutor misconduct','district attorney misconduct','solicitor misconduct','assistant district attorney','ADA misconduct','DA conflict','prosecutor conflict','motion to disqualify prosecutor','disqualification of prosecutor','selective prosecution','vindictive prosecution','retaliatory prosecution','bad faith prosecution','Brady violation','Giglio violation','withheld evidence','suppression of evidence','false testimony','perjury by witness','witness intimidation','abuse of discretion prosecutor','conflict of interest prosecutor','improper ex parte','law enforcement misconduct','probation misconduct','accountability court','treatment court','veterans court','drug court','mental health court','probation revocation','prosecutorial retaliation','First Amendment retaliation'],
  'Motions to Seal / Protective Orders / Confidentiality': ['motion to seal','order sealing record','sealed record','seal records','protective order','confidentiality order','motion for protective order','order granting protective order','privacy','redaction','minor child','confidential information','medical records','therapy records','school records','financial records','domestic violence','family violence','restraining order','temporary protective order','TPO','injunction','gag order','prior restraint','public access','First Amendment access','open courts','public records','court records access'],
  'Appeals / Reversals / Vacatur': ['reversed','vacated','remanded','vacated and remanded','abuse of discretion','clear error','due process','fundamental fairness','lack of findings','insufficient findings','no evidence','manifest abuse','arbitrary','capricious','error of law','harmless error','plain error','structural error','custody reversed','divorce reversed','contempt reversed','sanctions reversed','recusal reversed','GAL report appeal','guardian ad litem appeal','family court appeal','domestic relations appeal','custody modification appeal','termination of parental rights appeal','dependency appeal','juvenile court appeal'],
  'Custody / Parenting Time / Supervised Visitation': ['custody','child custody','legal custody','physical custody','parenting time','visitation','supervised visitation','no-contact order','parent-child contact','parental rights','fundamental right to parent','family integrity','best interest of the child','custody modification','emergency custody','ex parte custody','temporary custody','final custody order','parenting plan','parental alienation','reunification','reunification therapy','gatekeeping','domestic violence allegations','child abuse allegations','neglect allegations','DFCS','CPS','dependency','deprivation','juvenile court','legitimation','paternity','third-party custody','grandparent visitation','contempt custody','relocation'],
  'Due Process / Constitutional Family Law': ['due process','procedural due process','substantive due process','equal protection','First Amendment','retaliation','freedom of speech','access to courts','right to parent','parental rights','family integrity','vagueness','overbreadth','prior restraint','unconstitutional condition','improper delegation','no notice','lack of notice','lack of service','opportunity to be heard','evidentiary hearing','findings of fact','conclusions of law','temporary order','final order','void order','void judgment','jurisdiction','UCCJEA','subject matter jurisdiction','personal jurisdiction'],
  'Court Officials / Court Staff / Clerks': ['clerk misconduct','court clerk error','docketing error','missing filing','refused filing','filing rejected','ex parte order','improper docket entry','docket irregularity','altered docket','missing transcript','transcript error','court reporter','court administrator','case manager','judicial assistant','staff attorney','law clerk','improper communication','administrative order','local rule violation','clerk of court','superior court clerk','district clerk','county clerk','family court clerk'],
  'Public Records / Open Records / FOIA': ['open records','public records','FOIA','freedom of information','sunshine law','records request','open records request','denied records','withheld records','redacted records','improper redaction','attorney review fees','metadata','audit trail','email records','bodycam','transcript request','court audio','docket access','public access to court records','confidentiality claim','exemption','privilege log'],
  'Discipline / Ethics / Oversight': ['disciplinary order','public reprimand','private reprimand','suspension','disbarment','censure','admonition','judicial discipline','attorney discipline','bar discipline','judicial qualifications','judicial conduct','ethics complaint','bar complaint','grievance','probable cause','formal charges','consent order','settlement discipline','professional conduct','canon violation','code of judicial conduct','rules of professional conduct','conflict of interest','trust account','client funds','dishonesty','misrepresentation','neglect of client matter'],
  'Orders / Motions / Filings General': ['order','motion','emergency motion','ex parte motion','verified motion','affidavit','petition','complaint','amended complaint','response','objection','opposition','reply','notice','hearing notice','transcript','order after hearing','temporary order','final order','consent order','protective order','contempt order','sanctions order','attorney fee order','findings of fact','conclusions of law','memorandum opinion','bench ruling','oral ruling'],
  'Domestic Violence / Protective Orders / Weaponization Concerns': ['domestic violence','family violence','protective order','temporary protective order','restraining order','injunction','stalking','aggravated stalking','harassment','coercive control','litigation abuse','weaponized protective order','false allegations','custody leverage','no contact','Our Family Wizard','parenting app','supervised exchange','safe exchange','domestic relations','family court'],
  'Child Protective Services / Dependency': ['CPS','DFCS','child protective services','dependency','deprivation','neglect','abuse allegations','safety plan','family preservation','removal','non-removal','investigation','case plan','juvenile court','guardian ad litem juvenile','court appointed special advocate','CASA','foster care','reunification plan','termination of parental rights','TPR','mandated reporter','anonymous report','unfounded','substantiated','indicated']
};
const COVERED_STATES = ['Georgia','Florida','California','Ohio','South Carolina','Texas'];
const TRACKED_ROLES = ['Judge','Attorney/Lawyer','Guardian ad Litem','Prosecutor','Custody Evaluator','Parenting Coordinator','Court Staff','Expert/Witness','Agency/Office','Other Legal Professional'];
const DATA_ROOT = process.env.RECORD_ROOM_DATA || '/record-room-data';
const RECORD_ROOM_API_URL = process.env.RECORD_ROOM_API_URL || 'http://localhost:5173';
const RECORD_ROOM_ADMIN_TOKEN = process.env.RECORD_ROOM_ADMIN_TOKEN || 'local-dev-admin';
const SCANNER_PORT = process.env.SCANNER_PORT || 3000;
function source(source_name, source_category, opts = {}) {
  return {
    source_id: opts.source_id || source_name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), source_name, source_category,
    state: opts.state || null, county: opts.county || null, court: opts.court || null, base_url: opts.base_url || null,
    source_type: opts.source_type || source_category, access_type: opts.access_type || 'manual import', automation_status: opts.automation_status || 'manual import only',
    terms_notes: opts.terms_notes || 'Use only permitted public/API/manual import workflows. Do not bypass access controls.', robots_notes: opts.robots_notes || 'Check robots/terms before configuring automation.',
    login_required: !!opts.login_required, paid_access: !!opts.paid_access, captcha_likely: !!opts.captcha_likely, rate_limit: opts.rate_limit || 'manual/API-specific',
    safe_to_run_boolean: !!opts.safe_to_run_boolean, notes: opts.notes || 'placeholder/manual import/API required'
  };
}
const SCANNER_SOURCES = [
  source('Mock Connector','Open/API legal databases',{source_id:'mock-connector',access_type:'API',automation_status:'working connector',safe_to_run_boolean:true,notes:'Safe local test connector only; creates TEST DATA ONLY raw results.'}),
  source('CourtListener','Open/API legal databases',{source_id:'courtlistener',base_url:'https://www.courtlistener.com/api/rest/v4/',access_type:'API',automation_status:'working connector',safe_to_run_boolean:true,rate_limit:'Respect CourtListener API limits',notes:'Public API connector for opinions/search; results remain admin-only.'}),
  source('CourtListener RECAP','Open/API legal databases',{source_id:'courtlistener-recap',base_url:'https://www.courtlistener.com/recap/',access_type:'API',automation_status:'API required',notes:'Use CourtListener/RECAP API where available.'}),
  source('CourtListener Search API','Open/API legal databases',{source_id:'courtlistener-search-api',base_url:'https://www.courtlistener.com/api/rest/v4/search/',access_type:'API',automation_status:'working connector',safe_to_run_boolean:true}),
  ...['Caselaw Access Project / CourtListener CAP integration','Google Scholar case law manual search lead','Justia cases/manual source','FindLaw cases/manual source','Public.Resource.Org/manual source'].map(n=>source(n,'Open/API legal databases')),
  ...['PACER manual/API-configured source','PACER Case Locator manual/API-configured source','RECAP Archive via CourtListener','Federal district court dockets via RECAP where available','Federal appellate opinions','Federal bankruptcy dockets via RECAP where available'].map(n=>source(n,'Federal records',{login_required:/PACER/.test(n),paid_access:/PACER/.test(n),access_type:/RECAP|appellate/.test(n)?'API':'manual import',automation_status:/RECAP/.test(n)?'API required':'manual import only'})),
  ...['Trellis Law','Westlaw','Lexis','UniCourt','Docket Alarm','vLex/Fastcase','Bloomberg Law','Law360','Lex Machina','Other commercial platform'].map(n=>source(n,'Commercial/legal research platforms',{login_required:true,paid_access:true,access_type:'licensed export',automation_status:'manual import only',notes:'This source is treated as a manual/import research lead source unless approved API or license-compatible export is configured. Do not scrape or bypass access controls.'})),
  ...['Georgia re:SearchGA manual/API-configured source','Georgia appellate opinions','Georgia Supreme Court opinions','Georgia Court of Appeals opinions','Georgia Judicial Council/AOC court resources','Georgia county clerk/superior court portals','Georgia superior court docket portals','Georgia state court docket portals','Georgia magistrate court portals','Georgia probate court portals','Georgia juvenile court portals where public access exists','Georgia family/domestic case portals where public access exists','Cobb County Superior Court Clerk','Cherokee County Clerk of Courts','Fulton County Superior Court','DeKalb County Superior Court','Gwinnett County Clerk of Court','Clayton County Clerk of Court','Bartow County Clerk of Court','Paulding County Clerk of Court','Forsyth County Clerk of Court','Chatham County Clerk of Court','Richmond County Clerk of Court','Muscogee County Clerk of Court','Bibb County Clerk of Court','Hall County Clerk of Court','Henry County Clerk of Court','Douglas County Clerk of Court','Official Georgia Bar attorney discipline/manual source','Georgia Judicial Qualifications Commission/manual source','Georgia government/open records manual source'].map(n=>source(n,'Georgia sources',{state:'Georgia'})),
  ...['Florida appellate opinions','Florida Supreme Court opinions','Florida District Courts of Appeal opinions','Florida eCaseView/county clerk portals where available','Florida county clerk of court portals','Florida family court/domestic relations docket portals where public access exists','Miami-Dade Clerk of Courts','Broward County Clerk of Courts','Palm Beach County Clerk','Orange County Clerk','Hillsborough County Clerk','Pinellas County Clerk','Duval County Clerk','Lee County Clerk','Collier County Clerk','Sarasota County Clerk','Seminole County Clerk','Osceola County Clerk','Volusia County Clerk','Brevard County Clerk','Polk County Clerk','Pasco County Clerk','Manatee County Clerk','Alachua County Clerk','Florida Bar discipline/manual source','Florida Judicial Qualifications Commission/manual source'].map(n=>source(n,'Florida sources',{state:'Florida'})),
  ...['California appellate opinions','California Supreme Court opinions','California Courts of Appeal opinions','California superior court county portals','California family law case portals where public access exists','Los Angeles Superior Court','Orange County Superior Court','San Diego Superior Court','Riverside Superior Court','San Bernardino Superior Court','Santa Clara Superior Court','Alameda Superior Court','Sacramento Superior Court','Contra Costa Superior Court','Fresno Superior Court','Kern Superior Court','Ventura Superior Court','San Francisco Superior Court','San Mateo Superior Court','Sonoma Superior Court','Placer Superior Court','Monterey Superior Court','California State Bar discipline/manual source','California Commission on Judicial Performance/manual source'].map(n=>source(n,'California sources',{state:'California'})),
  ...['Ohio Supreme Court opinions','Ohio appellate opinions','Ohio county clerk/common pleas portals','Ohio domestic relations court portals','Franklin County Clerk of Courts','Cuyahoga County Clerk of Courts','Hamilton County Clerk of Courts','Montgomery County Clerk of Courts','Summit County Clerk of Courts','Lucas County Clerk of Courts','Stark County Clerk of Courts','Butler County Clerk of Courts','Lorain County Clerk of Courts','Mahoning County Clerk of Courts','Lake County Clerk of Courts','Warren County Clerk of Courts','Clermont County Clerk of Courts','Delaware County Clerk of Courts','Ohio attorney discipline/manual source','Ohio Board of Professional Conduct/manual source','Ohio judicial discipline/manual source'].map(n=>source(n,'Ohio sources',{state:'Ohio'})),
  ...['South Carolina Judicial Branch Public Index','South Carolina C-Track appellate access','South Carolina Supreme Court opinions','South Carolina Court of Appeals opinions','South Carolina county family court/public index portals','Greenville County Public Index','Charleston County Public Index','Richland County Public Index','Lexington County Public Index','Spartanburg County Public Index','Horry County Public Index','York County Public Index','Beaufort County Public Index','Anderson County Public Index','Berkeley County Public Index','Dorchester County Public Index','Aiken County Public Index','Sumter County Public Index','Florence County Public Index','South Carolina Bar discipline/manual source','South Carolina Judicial Conduct/manual source'].map(n=>source(n,'South Carolina sources',{state:'South Carolina'})),
  ...['re:SearchTX manual/API-configured source','Texas appellate opinions','Texas Supreme Court opinions','Texas Courts of Appeals opinions','Texas county clerk portals','Texas district clerk portals','Texas family court/district court portals where public access exists','Harris County District Clerk','Dallas County District Clerk','Tarrant County District Clerk','Bexar County District Clerk','Travis County District Clerk','Collin County District Clerk','Denton County District Clerk','Fort Bend County District Clerk','Montgomery County District Clerk','Williamson County District Clerk','Hidalgo County District Clerk','El Paso County District Clerk','Nueces County District Clerk','Galveston County District Clerk','Brazoria County District Clerk','Texas State Bar discipline/manual source','Texas State Commission on Judicial Conduct/manual source'].map(n=>source(n,'Texas sources',{state:'Texas'})),
  ...['State bar discipline pages','Attorney registration pages','Judicial qualifications commissions','Judicial conduct commissions','Prosecuting attorney council/directories','District attorney office pages','Public defender/appointed counsel lists','GAL appointment rosters where public','Court-appointed professional rosters','State court administrative office resources','Court rules pages','Ethics opinions pages'].map(n=>source(n,'Official discipline / oversight / ethics sources')),
  ...['Local news source/manual lead','National news source/manual lead','Google search manual lead','Bing search manual lead','Court press release/manual lead','Government press release/manual lead','Social media/public post/manual lead with caution'].map(n=>source(n,'News/public web sources'))
];
module.exports = { REVIEW_STATUSES, VISIBILITY_STATUSES, RELIABILITY_LABELS, RELIABILITY_TAGS, KEYWORD_GROUPS, COVERED_STATES, TRACKED_ROLES, DATA_ROOT, RECORD_ROOM_API_URL, RECORD_ROOM_ADMIN_TOKEN, SCANNER_PORT, SCANNER_SOURCES };
