(async function(){
 const app=document.getElementById('app');
 const [sources,groups,jobs,status]=await Promise.all([fetch('/api/sources').then(r=>r.json()),fetch('/api/keyword-groups').then(r=>r.json()),fetch('/api/admin/scanner-jobs').then(r=>r.json()),fetch('/api/admin/record-room/status').then(r=>r.json())]);
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const categories=[...new Set(sources.map(s=>s.source_category||'Other'))];
 const groupedOptions=categories.map(cat=>`<optgroup label="${esc(cat)}">${sources.filter(s=>(s.source_category||'Other')===cat).map(s=>`<option value="${s.id}" data-category="${esc(cat)}">${esc(s.name)} — ${esc(s.automation_status||s.access_method)}${s.safe_to_run_boolean?'':' (manual/API required)'}</option>`).join('')}</optgroup>`).join('');
 app.innerHTML=`<div class="card"><h2>Record Room AI Connection</h2><p><span class="badge">${status.connected?'connected':'disconnected'}</span> API URL: <b>${esc(status.apiUrl)}</b></p><p>Last import status: ${esc(JSON.stringify(status.lastImportStatus||{}))}</p><button onclick="sendNew()">Send all new results to Record Room AI</button><a class="badge" href="/admin/raw-results">Raw results</a><a class="badge" href="/admin/review">Review queue</a></div>
 <div class="card"><h2>Run scanner job</h2><p class="muted">Working connectors run only for safe API/open sources. Manual/API-required sources create instructions instead of scraping.</p><form id="f"><div class="grid"><label>Source category<select class="big" name="source_category"><option value="">All categories</option>${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label>Specific source<select class="big" name="source_id" required>${groupedOptions}</select></label><label>State<input name="state" placeholder="State"></label><label>County<input name="county" placeholder="County"></label><label>Court<input name="court" placeholder="Court"></label><label>Case type<input name="case_type" placeholder="opinion, civil, family, probate..."></label><label>Keyword group<select class="big" name="keyword_group">${groups.map(g=>`<option>${esc(g.name)}</option>`).join('')}</select></label><label>Custom keywords<textarea name="custom_keywords" placeholder="comma-separated exact phrases"></textarea></label><label>Person/entity name<input name="person_name" placeholder="Name"></label><label>Role<input name="role" placeholder="Judge, GAL, attorney..."></label><label>Date start<input type="date" min="1990-01-01" name="date_start"></label><label>Date end<input type="date" min="1990-01-01" name="date_end"></label><label>Max results<input type="number" min="1" max="100" name="max_results" value="5"></label><label>Result handling<select name="result_handling"><option>save locally only</option><option>send to Record Room AI</option><option>both</option></select></label></div><div class="card"><label><input type="checkbox" name="include_official_only" value="1"> include official sources only</label><label><input type="checkbox" name="include_manual_sources" value="1" checked> include manual/import sources as leads</label><label><input type="checkbox" name="include_commercial_leads" value="1"> include commercial platform leads</label><label><input type="checkbox" name="exclude_login_captcha" value="1" checked> exclude source types requiring login/CAPTCHA</label></div><button>Run job</button><button class="secondary" type="button" onclick="createLead()">Create research lead instead</button><button class="secondary" type="button" onclick="testConnector()">Test connector</button><button class="secondary" type="button" onclick="sendNew()">Send all new results to Record Room AI</button></form><pre id="out"></pre></div>
 <div class="card"><h2>Source safety notes</h2><p class="warn danger">Trellis/Westlaw/Lexis/UniCourt/Docket Alarm: This source is treated as a manual/import research lead source unless approved API or license-compatible export is configured. Do not scrape or bypass access controls.</p><div id="sourceMeta"></div></div>
 <div class="card"><h2>Expanded keyword groups</h2>${groups.map(g=>`<details><summary><b>${esc(g.name)}</b></summary><p>${esc(JSON.parse(g.keywords).join(', '))}</p></details>`).join('')}</div>
 <div class="card"><h2>Recent jobs</h2><table><tr><th>ID</th><th>Source</th><th>Status</th><th>Results</th><th>Error/log</th><th>Created</th></tr>${jobs.map(j=>`<tr><td>${j.id}</td><td>${esc(j.source_name)}</td><td>${esc(j.status)}</td><td>${j.results_count||0}</td><td>${esc(j.error_message||j.last_log||'')}</td><td>${esc(j.created_at)}</td></tr>`).join('')}</table></div>`;
 function selectedSource(){return sources.find(s=>String(s.id)===String(document.querySelector('[name=source_id]').value));}
 function renderMeta(){const s=selectedSource();document.getElementById('sourceMeta').innerHTML=s?`<p><span class="badge">${esc(s.access_type||s.access_method)}</span><span class="badge">${esc(s.automation_status)}</span><span class="badge">safe to run: ${s.safe_to_run_boolean?'yes':'no'}</span></p><p>${esc(s.notes)}</p><p><b>Terms:</b> ${esc(s.terms_notes)}<br><b>Robots:</b> ${esc(s.robots_notes)}<br><b>Login:</b> ${s.login_required?'yes':'no'} <b>Paid:</b> ${s.paid_access?'yes':'no'} <b>CAPTCHA likely:</b> ${s.captcha_likely?'yes':'no'}</p>`:'';}
 document.querySelector('[name=source_id]').onchange=renderMeta;renderMeta();
 document.getElementById('f').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));const r=await fetch('/api/admin/scanner-jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});document.getElementById('out').textContent=JSON.stringify(await r.json(),null,2);};
 window.createLead=()=>{location.href='/admin/research-leads'}; window.testConnector=()=>{document.querySelector('[name=source_id]').value=String((sources.find(s=>s.source_id==='mock-connector')||sources[0]).id);document.getElementById('f').requestSubmit();};
 window.sendNew=async()=>{const r=await fetch('/api/admin/record-room/send-new',{method:'POST'});document.getElementById('out').textContent=JSON.stringify(await r.json(),null,2);};
})();
