(async function(){
 const app=document.getElementById('app');const rows=await fetch('/api/admin/raw-results').then(r=>r.json());
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uniq=k=>[...new Set(rows.map(r=>r[k]).filter(Boolean))].sort();
 app.innerHTML=`<p>Raw scanner/API results are never public automatically. Use filters for source, source category, state, county, court, role, keyword group, review status, confidence, and date.</p><div class="card grid"><label>Source<select id="source"><option></option>${uniq('source_name').map(v=>`<option>${esc(v)}</option>`)}</select></label><label>Source category<select id="source_category"><option></option>${uniq('source_category').map(v=>`<option>${esc(v)}</option>`)}</select></label><label>State<select id="state"><option></option>${uniq('state').map(v=>`<option>${esc(v)}</option>`)}</select></label><label>County<select id="county"><option></option>${uniq('county').map(v=>`<option>${esc(v)}</option>`)}</select></label><label>Court<select id="court"><option></option>${uniq('court').map(v=>`<option>${esc(v)}</option>`)}</select></label><label>Role<select id="role"><option></option>${uniq('role').map(v=>`<option>${esc(v)}</option>`)}</select></label><label>Keyword group<select id="keyword_group"><option></option>${uniq('keyword_group').map(v=>`<option>${esc(v)}</option>`)}</select></label><label>Review status<select id="review_status"><option></option>${uniq('review_status').map(v=>`<option>${esc(v)}</option>`)}</select></label><label>Minimum confidence<input id="confidence" type="number" step="0.01" min="0" max="1"></label><label>Date contains<input id="date" placeholder="YYYY-MM-DD"></label></div><div id="table"></div>`;
 function visible(r){for(const k of ['source_category','state','county','court','role','keyword_group','review_status']){const v=document.getElementById(k).value;if(v&&r[k]!==v)return false;}const source=document.getElementById('source').value;if(source&&r.source_name!==source)return false;const c=document.getElementById('confidence').value;if(c&&Number(r.confidence_score||0)<Number(c))return false;const d=document.getElementById('date').value;if(d&&!String(r.created_at||'').includes(d)&&!String(r.filing_date||'').includes(d)&&!String(r.event_date||'').includes(d))return false;return true;}
 function render(){const filtered=rows.filter(visible);document.getElementById('table').innerHTML=`<p>${filtered.length} result(s)</p><table><tr><th>ID</th><th>Source</th><th>State</th><th>County</th><th>Court</th><th>Case</th><th>Case #</th><th>Docket title</th><th>Document title</th><th>Keywords</th><th>Confidence</th><th>Status</th><th>Visibility</th><th>Created</th><th>Actions</th></tr>${filtered.map(r=>`<tr><td>${r.id}</td><td>${esc(r.source_name)}</td><td>${esc(r.state)}</td><td>${esc(r.county)}</td><td>${esc(r.court)}</td><td>${esc(r.case_name)}</td><td>${esc(r.case_number)}</td><td>${esc(r.docket_entry_title)}</td><td>${esc(r.document_title)}</td><td>${esc(r.matched_keywords)}</td><td>${esc(r.confidence_score)}</td><td>${esc(r.review_status)}</td><td>${esc(r.visibility)}</td><td>${esc(r.created_at)}</td><td><button onclick="update(${r.id},'likely relevant')">mark relevant</button><button onclick="update(${r.id},'not relevant')">mark not relevant</button><button onclick="update(${r.id},'duplicate')">mark duplicate</button><button onclick="update(${r.id},'needs official source verification')">needs official verification</button><button onclick="update(${r.id},'needs redaction')">needs redaction</button><button onclick="update(${r.id},'approved private')">approve private</button><button onclick="update(${r.id},'approved public')">approve public</button><button onclick="update(${r.id},'rejected')">reject</button><button onclick="sendRR(${r.id})">send to Record Room AI</button><button onclick="alert('Attach/create profile is available from /admin/profiles when local profiles are used.')">attach/create profile</button></td></tr>`).join('')}</table>`;}
 for(const id of ['source','source_category','state','county','court','role','keyword_group','review_status','confidence','date'])document.getElementById(id).oninput=render;render();
 window.update=async(id,review_status)=>{await fetch(`/api/admin/raw-results/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({review_status})});location.reload();};
 window.sendRR=async id=>{const r=await fetch(`/api/admin/raw-results/${id}/send-record-room`,{method:'POST'});alert(JSON.stringify(await r.json(),null,2));};
})();
